#!/bin/bash -l
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=20
#SBATCH -t 1:00:00
#SBATCH --cpus-per-task=1
#SBATCH -J SPCE_properties

module load intel intel-mpi


export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun $HOME/.local/bin/lmp_tigercpu -sf omp -in lammps.in

